export const INCREMENT_BY_ONE="INCREMENT_BY_ONE"
export const DECREMENT_BY_ONE="DECREMENT_BY_ONE"
export const INCREMENT_BY_NUMBER="INCREMENT_BY_NUMBER"
export const DECREMENT_BY_NUMBER="DECREMENT_BY_NUMBER"